server:
  port: 8080
spring:
  redis:
    host: localhost
    port: 6379
    password: 928292
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reggie?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 928292
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id

reggie:
  path: E:\reggie\image\